# START OF MODIFIED pubspec.yaml
name: underground_rap_clicker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15 # Оставляем вашу версию (последняя ^2.5.2)
  audioplayers: ^6.1.0       # Оставляем вашу версию (последняя ^6.2.0)
  # google_fonts: ^6.2.1  <--- УДАЛИТЕ ЭТУ СТРОКУ

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Оставляем вашу версию (последняя ^4.0.0)

flutter:
  uses-material-design: true

  assets:
    - assets/audio/blonde.mp3
    - assets/audio/For Da Flex.mp3
    - assets/audio/All Star.mp3
    - assets/audio/Baghdad.mp3
    - assets/audio/Congrats.mp3
    - assets/audio/Talking 2 A Ghost.mp3
    - assets/audio/Pop.mp3
    - assets/audio/Str8 Flexin.mp3
    - assets/audio/Me When.mp3
    - assets/audio/Uno.mp3
    - assets/audio/Kills.mp3
    - assets/audio/Kome Thru.mp3
    - assets/audio/Boss Up.mp3
    - assets/audio/3x.mp3
    - assets/audio/Worst Part.mp3
    - assets/audio/Trenches.mp3
    - assets/audio/Nothing.mp3
    - assets/images/blonde_cover.png
    - assets/images/game_background.png # Убедитесь, что все ассеты перечислены
    - assets/images/clickable_rapper.png
    - assets/images/clout_coin.png
    - assets/images/upgrade_row_bg.png
    - assets/images/upgrade_button_active.png
    # --- Добавляем путь к папке шрифтов ---
    - assets/fonts/ # Это не обязательно, но полезно для ясности

  # --- Добавляем секцию fonts ---
  fonts:
    - family: Galindo # Это имя будем использовать в коде
      fonts:
        - asset: assets/fonts/Galindo-Regular.ttf # Укажите ТОЧНОЕ имя вашего файла .ttf
        # Если есть другие стили (Bold, Italic), добавьте их сюда:
        # - asset: assets/fonts/Galindo-Bold.ttf
        #   weight: 700
  # ---------------------------

# END OF MODIFIED pubspec.yaml
