name: Build Flutter APK

on:
  # Запускать сборку вручную (workflow_dispatch),
  # либо при push на ветку main (или любую другую ветку).
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Скачиваем код репозитория
      - uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Flutter (через subosito/flutter-action)
      - uses: subosito/flutter-action@v2
        with:
          channel: stable  # Можно stable, beta, dev

      # Шаг 3: Устанавливаем зависимости
      - name: Install dependencies
        run: flutter pub get

      # Шаг 4: Собираем APK в релизном режиме
      - name: Build APK (release)
        run: flutter build apk --release

      # Шаг 5: Загружаем APK как артефакт
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk