name: Build Flutter APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        working-directory: underground_rap_clicker
        run: flutter pub get

      - name: Build APK (release)
        working-directory: underground_rap_clicker
        run: flutter build apk --release

      - name: Upload APK
        working-directory: underground_rap_clicker
        uses: actions/upload-artifact@v4.6.1
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
