name: Build Flutter APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Все run-степы будут выполняться в каталоге underground_rap_clicker
        working-directory: underground_rap_clicker

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK
        # Для шага, использующего "uses", настройка working-directory не применяется,
        # поэтому путь указываем относительно корня репозитория.
        uses: actions/upload-artifact@v4.6.1
        with:
          name: release-apk
          path: underground_rap_clicker/build/app/outputs/flutter-apk/app-release.apk
